input {
  file {
    path => "/logs/logs.jsonl"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "news-api-logs"
  }
  stdout { codec => rubydebug }
}
